// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACard: typeof import('@arco-design/web-vue')['Card']
    BaseDrawDown: typeof import('./src/components/base-draw-down/index.vue')['default']
    BaseEditInfo: typeof import('./src/components/base-edit-info/index.vue')['default']
    BaseSignForm: typeof import('./src/components/base-sign-form/index.vue')['default']
    BaseSignOut: typeof import('./src/components/base-sign-out/index.vue')['default']
    BaseSvgIcon: typeof import('./src/components/base-svg-icon/index.vue')['default']
    BaseSwitch: typeof import('./src/components/base-switch/index.vue')['default']
    BaseUserInfo: typeof import('./src/components/base-user-info/index.vue')['default']
    McContainer: typeof import('./src/components/mc-container/index.vue')['default']
    McParticularsComment: typeof import('./src/components/mc-particulars-comment/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
